import { cn } from "@/lib/utils";

/**
 * "Bubbles" — the app's pixelated cauldron mascot. One character, three moods.
 * Each pose is a static, theme-agnostic SVG under /public/mascot (generated by
 * scripts/generate-mascot.mjs). Render it at any size via `className`.
 *
 *   <Mascot pose="sleep" className="size-28" />
 *
 * Three cauldron designs: witch-hat, bubbly (zigzag mouth), and magic-wand.
 * Decorative by default (aria-hidden). Pass `alt` when it carries meaning.
 */
export type MantaPose = "glide" | "wave" | "cheer" | "sleep" | "dive" | "peek";

export function Mascot({
  pose = "glide",
  className,
  alt,
}: {
  pose?: MantaPose;
  className?: string;
  alt?: string;
}) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={`/mascot/manta-${pose}.svg`}
      alt={alt ?? ""}
      aria-hidden={alt ? undefined : true}
      draggable={false}
      className={cn("block size-16 select-none", className)}
    />
  );
}
